---

- name: Arista Cleanup
  hosts: arista

  tasks:
    - name: Configure Ethernet2-4 for access mode, VLAN1
      eos_switchport: name={{ item }} mode=access access_vlan=1 trunk_allowed_vlans=1-4094 trunk_native_vlan=1
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }} 
            port={{ eapi_port }}
            transport=https
      with_items:
        - Ethernet2
        - Ethernet3
        - Ethernet4
 
    - name: Reset Ethernet4 description to default
      eos_interface: name=Ethernet4 description=""   
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }} 
            port={{ eapi_port }}
            transport=https
    - name: Remove VLANs
      eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }} 
            port={{ eapi_port }}
            transport=https
      with_items:
        - {name: BLUE, vlanid: 100}
        - {name: RED, vlanid: 200}
        - {name: GREEN, vlanid: 300}

    - name: Cleanup LAG
      eos_portchannel: name=Port-Channel1 state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }} 
            port={{ eapi_port }}
            transport=https













    
