---

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: Create the VLANs !!!
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}}      
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
      with_items:
        - {name: BLUE, vlanid: 100}
        - {name: RED, vlanid: 200}
        - {name: GREEN, vlanid: 300}



#    - name: create BLUE VLAN
#      eos_vlan: name=BLUE vlanid=100
#           username={{ eapi_username }}
#           password={{ eapi_password }}
#           host={{ eapi_hostname }}
#           port={{ eapi_port }}
#           transport=https
#    
#    - name: create RED VLAN
#      eos_vlan: name=RED vlanid=200
#            username={{ eapi_username }}
#            password={{ eapi_password }}
#            host={{ eapi_hostname }}
#            port={{ eapi_port }}
#            transport=https
#
#    - name: create GREEN VLAN
#      eos_vlan:  name=GREEN vlanid=300
#            username={{ eapi_username }}
#            password={{ eapi_password }}
#            host={{ eapi_hostname }}
#            port={{ eapi_port }}
#            transport=https

    - name: Setting Ethernet2-4 to access mode, VLANID
      eos_switchport: name={{ item.port }} mode=access access_vlan={{ item.vlanid }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https  
      with_items:
            - {port: Ethernet2, vlanid: 100}
            - {port: Ethernet3, vlanid: 200}
            - {port: Ethernet4, vlanid: 300}

#    - name: Remove VLANs
#     eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
#            username={{ eapi_username }}
#            password={{ eapi_password }}
#            host={{ eapi_hostname }}
#            port={{ eapi_port }}
#            transport=https
#      with_items:
#        - {name: BLUE, vlanid: 100}
#        - {name: RED, vlanid: 200}
#        - {name: GREEN, vlanid: 300}

























  
