---

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: create BLUE VLAN
      eos_vlan: name=BLUE vlanid=100
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
    
    - name: create RED VLAN
      eos_vlan: name=RED vlanid=200
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create GREEN VLAN
      eos_vlan:  name=GREEN vlanid=300
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet4 description
      eos_interface: name=Ethernet4 description="*** TESTING ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https  

    - name: Setting Ethernet2-4 to access mode, VLAN200
      eos_switchport: name={{ item }} mode=access access_vlan=200
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https  
       
      with_items:
            - Ethernet2
            - Ethernet3
            - Ethernet4


























  
