---
- name: Configure primary Ethernet Interface
  hosts: arista
  tasks: 

    - name: Setting Ethernet4 description
      eos_interface: name=Ethernet4 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
    - name: Setting Ethernet4 to access mode, VLAN105
      eos_switchport: name=Ethernet4 mode=access access_vlan=105
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https







