---
- hosts: localhost
  tasks: 
    - name: Generate Configuration File
      template: src=/home/mohalloran/TEST_EXERCISE1/access_switch.j2
                    dest=/home/mohalloran/TEST_EXERCISE1/CFGS/{{item.hostname}}.txt
      with_items:
        - { hostname: access_switch1 , ip_addr: 1.1.1.1 }
        - { hostname: access_switch2 , ip_addr: 1.1.1.2 }        
        - { hostname: access_switch3 , ip_addr: 1.1.1.3 }         
        - { hostname: access_switch4 , ip_addr: 1.1.1.4 }       
        - { hostname: access_switch5 , ip_addr: 1.1.1.5 }        
        - { hostname: access_switch6 , ip_addr: 1.1.1.6 }        



 
